name: adaptive_locale
description: The easiest way to handle Locales in your Flutter app
  and preserves locale changes across app restarts.
version: 1.0.0
homepage: https://github.com/DamianAldair/adaptive_locale
repository: https://github.com/DamianAldair/adaptive_locale

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=2.0.1 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
