name: adaptive_locale
description:  Allows to change between locales dynamically.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=2.0.1 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
